### ISSUE TITLE
Support OctoberCMS plugin config features without ServiceProvider

### ISSUE THREAD

**Issue by LukeTowers** [isswp101/oc-page-settings-plugin#1]
You don't need to have a service provider to publish a config file to the project config, you can just use a plugin based config file to have October register it and handle project-level overrides: http://octobercms.com/docs/plugin/settings#file-configuration

**Comment by devemio** [comment]
@LukeTowers yeah, that's a good idea. Thanks so much for reviewing and feedback.

**Comment by devemio** [comment]
@LukeTowers fixed in `1.1.0` version.

**Comment by LukeTowers** [comment]
@isswp101 Thanks!
